# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Tar-Wrapper
version:      0.02
version_from: lib/Archive/Tar/Wrapper.pm
installdirs:  site
requires:
    Cwd:                           0
    File::Temp:                    0
    Log::Log4perl:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
